package cn.edu.xmu.provider.mapper;

import cn.edu.xmu.provider.model.po.GoodsCategoryPo;
import cn.edu.xmu.provider.model.po.GoodsCategoryPoExample;
import java.util.List;

public interface GoodsCategoryPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated
     */
    int insert(GoodsCategoryPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated
     */
    int insertSelective(GoodsCategoryPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated
     */
    List<GoodsCategoryPo> selectByExample(GoodsCategoryPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated
     */
    GoodsCategoryPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodsCategoryPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsCategoryPo record);
}